name: Publish docs via GitHub Pages

#on:
#  push:
#    branches: [ main ]

#jobs:
#  build:
#    name: Deploy docs
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout main
#        uses: actions/checkout@v2
#
#      - uses: actions/setup-python@v2
#        with:
#          python-version: 'pypy-3.6'

#      - name: Deploy docs
#        uses: chrisbues/mkdocs-gh-pages-action@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          #GITHUB_DOMAIN: github.myenterprise.com

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      #- run: sudo apt install weasyprint -y
      #- run: pip install mkdocs-material mkdocs-pdf-export-plugin
      - run: pip install mkdocs-material mkdocs-page-pdf
      - run: mkdocs gh-deploy --force
